### ISSUE TITLE
Compatibility with pymbar 3.0.5

### ISSUE THREAD

**Issue by xiki-tempula** [MobleyLab/alchemical-analysis#124]
I used to use alchemical analysis with pymbar 3.0.dev3, which works fine.
I have recently reinstalled the alchemical analysis but with the latest version of pymbar 3.0.5. However, it seems that using the pymbar 3.0.5 would give error 
```
Estimating the free energy change with MBAR...
The overlap matrix is...
Traceback (most recent call last):
  File "../../../../../anaconda2/bin/alchemical_analysis", line 11, in <module>
    load_entry_point('alchemical-analysis==1.0.2.dev0', 'console_scripts', 'alchemical_analysis')()
  File "/truba/home/XXX/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/alchemical_analysis/alchemical_analysis.py", line 1269, in main
    Deltaf_ij, dDeltaf_ij = estimatewithMBAR(u_kln, N_k, P.relative_tolerance, regular_estimate=True)
  File "/truba/home/XXX/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/alchemical_analysis/alchemical_analysis.py", line 334, in estimatewithMBAR
    O = MBAR.computeOverlap()[2]
KeyError: 2
```
Which is not encountered with pymbar 3.0.dev3.
I could upload the files for testing purposes.

**Comment by davidlmobley** [comment]
Alchemical analysis is no longer maintained; you want `alchemlyb` instead.

**Comment by orbeckst** [comment]
@xiki-tempula – there's no complete replacement for alchemical-analysis yet in https://github.com/alchemistry/alchemlyb ; you can try https://github.com/alchemistry/flamel, on which development has stopped because of lack of developers, but there's basic functionality. In any case, raise issues in alchemlyb and feel free to contribute: we desperately need people.
