### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by gayatripanda5** [MobleyLab/alchemical-analysis#129]
Hi, 
I would like to thank the developers of this tool for making our life easier. I have performed thermodynamic integration using AMBER. I have used 25 lambda windows and ran each window for 10ns. I was using this script for analysis as the AMBER tutorial lacks the analysis part in it. I was getting this error 
"Traceback (most recent call last):
  File "../../alchemical_analysis//alchemical_analysis.py", line 1293, in <module>
    main()
  File "../../alchemical_analysis//alchemical_analysis.py", line 1228, in main
    nsnapshots, lv, dhdlt, u_klt = parser_amber.readDataAmber(P)
  File "/home/gayatrip/FEP-tut/alchemical-analysis/alchemical_analysis/parser_amber.py", line 713, in readDataAmber
    _print_comps(dvdl_comps_all, len(DVDL_COMPS), P.units, Econv)
  File "/home/gayatrip/FEP-tut/alchemical-analysis/alchemical_analysis/parser_amber.py", line 305, in _print_comps
    ave = [a / len(Enes) for a in ave] # len(Enes) = no. of time steps/file
ZeroDivisionError: float division by zero"

Please help me resolve it. This is the first time I have performed any free-energy calculations, and I need some guidance in analyzing and interpreting the results. Thanks.

**Comment by davidlmobley** [comment]
This tool is obsolete/no longer maintained; you should be using alchemlyb instead.
