### ISSUE TITLE
Properly handle case of all zeros in all input .xvg files

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/alchemical-analysis#14]
Currently in this case the script fails with an exception due to a problem calculating the statistical inefficiency: 

Traceback (most recent call last):
  File "/home/pklimovi/analysis/alchemical-free-energy/alchemical_analysis.py", line 1099, in <module>
    dhdl, N_k, u_kln = uncorrelate(sta=numpy.zeros(K, int), fin=nsnapshots, do_dhdl=True)
  File "/home/pklimovi/analysis/alchemical-free-energy/alchemical_analysis.py", line 160, in uncorrelate
    g[k] = pymbar.timeseries.statisticalInefficiency(dhdl_sum)
  File "/home/pklimovi/analysis/pymbar-2.1.0-beta/pymbar/timeseries.py", line 178, in statisticalInefficiency
    raise ParameterError('Sample covariance sigma_AB^2 = 0 -- cannot compute statistical inefficiency')
pymbar.utils.ParameterError: Sample covariance sigma_AB^2 = 0 -- cannot compute statistical inefficiency

See for example /work/cluster/vjaber/normal_hydrations/CRASHED_TRAJ/1234_tetrachlorobenzene_to_4_chlorophenol_vac

We ought instead to catch this case earlier (i.e. when the data is loaded from the .xvg files) and print out a note along with a sensible results.txt file. (This is important in, for example, @limn1 's calculations since some calculations which yield zeros were accidentally run.)

**Comment by davidlmobley** [comment]
Resolved by #78 .
