### ISSUE TITLE
small ligand solvation energy calculation:error:cannot compute statistical inefficiency

### ISSUE THREAD

**Issue by sanasaeed** [MobleyLab/alchemical-analysis#83]
i have done ligand simulation in water and now wantto calculate solvation free energy , i used 31 lambdas states, i got this error by using alchemical_analysis.py.
 
Traceback (most recent call last):
  File "/share/anaconda2/bin/alchemical_analysis.py", line 4, in <module>
    __import__('pkg_resources').run_script('alchemical-analysis==1.0.2.dev0', 'alchemical_analysis.py')
  File "/share/anaconda2/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 724, in run_script
  File "/share/anaconda2/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1649, in run_script
  File "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py", line 1226, in <module>
    main()
  File "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py", line 1197, in main
    dhdl, N_k, u_kln = uncorrelate(sta=numpy.zeros(K, int), fin=nsnapshots, do_dhdl=True)
  File "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py", line 181, in uncorrelate
    g[k] = pymbar.timeseries.statisticalInefficiency(dhdl_sum)
  File "build/bdist.linux-x86_64/egg/pymbar/timeseries.py", line 178, in statisticalInefficiency
pymbar.utils.ParameterError: Sample covariance sigma_AB^2 = 0 -- cannot compute statistical inefficiency

**Comment by davidlmobley** [comment]
Should have been fixed by #78, I think. Please verify you're using a version you just installed (i.e. in the last 20 days), or download and install the latest directly from source and confirm this persists? 

Normally (prior to the fix) this issue arises only when you have a free energy difference which is identically zero between some (or all) of your lambda values, so in some sense the problem is with your data and not as much with the code, though the code OUGHT to handle this properly.

If you are using the latest version, can you provide a link to a Dropbox/Google Drive/etc. file with your data in it so we can troubleshoot?

**Comment by sanasaeed** [comment]
no i am using the older one. i will install the new one and will try again. where can i fine the description about the modifications you made in the new version. i want to know the difference from the older version. 
Thanks for your help

**Comment by limn1** [comment]
Hi Sanaa, since we don't have a version scheme implemented the changes would depend on when you first installed alchemical analysis. You can also view the commit log if you want to get into the details. In general, there have been some important fixes to primarily address this issue you are seeing and some issues with MBAR error totaling.

**Comment by sanasaeed** [comment]
hi Nathan Limthanks for replyi just wanted to see what are the changes you made. i'll see commit log

Sana Saeed Khan,Teaching-Research AssistantChemoinformatics LabGraduate Student, MS bioinfoDepartment of BioinformaticsSoongsil University, Seoul, South Korea. 

    On Thursday, March 10, 2016 11:15 AM, Nathan Lim <notifications@github.com> wrote:
 

 Hi Sanaa, since we don't have a version scheme implemented the changes would depend on when you first installed alchemical analysis. You can also view the commit log if you want to get into the details. In general, there have been some important fixes to primarily address this issue you are seeing and some issues with MBAR error totaling.—

**Comment by davidlmobley** [comment]
You should be able to get a fairly complete log of changes looking at the
list of closed pull requests here
https://github.com/MobleyLab/alchemical-analysis/pulls?q=is%3Apr+is%3Aclosed

You can also of course review detailed code changes associated with each.

Generally speaking, all of the changes have been bug fixes/extensions. I
don't think we've actually changed details of how anything works except how
decorrelation of correlated samples works in a very specific case.

Thanks.

On Wed, Mar 9, 2016 at 5:57 PM, Sana Saeed <notifications@github.com> wrote:

> no i am using the older one. i will install the new one and will try
> again. where can i fine the description about the modifications you made in
> the new version. i want to know the difference from the older version.
> Thanks for your help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/83#issuecomment-194617186>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436
