### ISSUE TITLE
 index 40 is out of bounds for axis 0 with size 40

### ISSUE THREAD

**Issue by sanasaeed** [MobleyLab/alchemical-analysis#87]
I am calculating binding free energy of Protein ligand complex, 41 lambdas. i got this error.
Traceback (most recent call last):
  File "/share/anaconda2/bin/alchemical_analysis.py", line 4, in <module>
    __import__('pkg_resources').run_script('alchemical-analysis==1.0.2.dev0', 'alchemical_analysis.py')
  File "/share/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/share/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py", line 1226, in <module>
    main()
  File "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py", line 1212, in main
    totalEnergies()
  File "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py", line 583, in totalEnergies
    dF[name] += df_allk[k][name]
IndexError: index 40 is out of bounds for axis 0 with size 40

**Comment by davidlmobley** [comment]
Can you please provide a link to your input (i.e. share a tarball of the
.xvg files via GitHub or similar)?

Thanks.

On Sun, Apr 24, 2016 at 11:16 PM, Sana Saeed <notifications@github.com>
wrote:

> I am calculating binding free energy of Protein ligand complex, 41
> lambdas. i got this error.
> Traceback (most recent call last):
> File "/share/anaconda2/bin/alchemical_analysis.py", line 4, in
> *import*('pkg_resources').run_script('alchemical-analysis==1.0.2.dev0',
> 'alchemical_analysis.py')
> File
> "/share/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/
> *init*.py", line 726, in run_script
> File
> "/share/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/
> *init*.py", line 1484, in run_script
> File
> "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py",
> line 1226, in
> main()
> File
> "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py",
> line 1212, in main
> totalEnergies()
> File
> "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py",
> line 583, in totalEnergies
> dF[name] += df_allk[k][name]
> IndexError: index 40 is out of bounds for axis 0 with size 40
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/87>
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by sanasaeed** [comment]
https://www.dropbox.com/s/csdf8v59z5cmqh5/complex.zip?dl=0

**Comment by sanasaeed** [comment]
i have sent you the dropbox link, can you see it? Sana Saeed Khan,Research AssistantChemoinformatics LabGraduate Student, MS bioinfoDepartment of BioinformaticsSoongsil University, Seoul, South Korea. 

    On Tuesday, April 26, 2016 12:31 AM, David L. Mobley <notifications@github.com> wrote:
 

 Can you please provide a link to your input (i.e. share a tarball of the
.xvg files via GitHub or similar)?

Thanks.

On Sun, Apr 24, 2016 at 11:16 PM, Sana Saeed <notifications@github.com>
wrote:

> I am calculating binding free energy of Protein ligand complex, 41
> lambdas. i got this error.
> Traceback (most recent call last):
> File "/share/anaconda2/bin/alchemical_analysis.py", line 4, in
> *import*('pkg_resources').run_script('alchemical-analysis==1.0.2.dev0',
> 'alchemical_analysis.py')
> File
> "/share/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/
> *init*.py", line 726, in run_script
> File
> "/share/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/
> *init*.py", line 1484, in run_script
> File
> "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py",
> line 1226, in
> main()
> File
> "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py",
> line 1212, in main
> totalEnergies()
> File
> "/share/anaconda2/lib/python2.7/site-packages/alchemical_analysis-1.0.2.dev0-py2.7.egg/EGG-INFO/scripts/alchemical_analysis.py",
> line 583, in totalEnergies
> dF[name] += df_allk[k][name]
> IndexError: index 40 is out of bounds for axis 0 with size 40
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/87>
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436
